<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--parent-->
    <parent>
        <groupId>com.cjq</groupId>
        <artifactId>answer-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../answer-parent/pom.xml</relativePath>
    </parent>


    <groupId>com.cjq</groupId>
    <artifactId>answer-mapper</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
<!--   pojo实体依赖         -->
            <groupId>com.cjq</groupId>
            <artifactId>answer-pojo</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

<!--MyBatis-Plus -->
        <!--MyBatis-Plus（Spring Boot 3 专用 starter）-->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- MySQL 驱动 -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>

    </dependencies>
</project>